name: xeus-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python=0.13.9
  - notebook
  - ipywidgets>=7.6
  - jupyterlab=3
  - itkwidgets
  - matplotlib
  - ipympl
